id: 'c05a7712-8a1b-4680-737f-08dd7ccec69f'
name: 'C3-X-DB-DV'
description: 'this is my eLearning Project with the Databricks DataVault and Mart generator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Spark.Databricks'
  version: '1.9.1'
sourceSystems:
  - id: '6c40c82f-b433-4b30-81bd-0fe662dcc9d2'
    name: 'stage_file'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
  - id: '51ea64da-e5f9-4f0d-8203-796ad28c899e'
    name: 'crm'
    description: ''
    activeDiscovery: 'e2c5eaea-28ed-4f66-b073-546a4965d0e4'
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
  - id: '47f997f6-b7fa-4f3d-96e0-ba6790483fed'
    name: 'stage_files_with_crm'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
propertyValues:
  - propertyId: '59eca19a-3bec-4169-85fd-41331f6fac3a'
    value: 'true'
  - propertyId: 'a9de64e6-8417-4f17-b491-4f105ed891a9'
    value: 'Sequential Notebook'
