id: 'c05a7712-8a1b-4680-737f-08dd7ccec69f'
name: 'C3-X-DB-DV'
description: 'this is my eLearning Project with the Databricks DataVault and Mart generator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Spark.Databricks'
  version: '1.8.0'
sourceSystems:
  - id: '6c40c82f-b433-4b30-81bd-0fe662dcc9d2'
    name: 'stage_file'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
propertyValues:
  - propertyId: '59eca19a-3bec-4169-85fd-41331f6fac3a'
    value: 'true'
  - propertyId: 'a9de64e6-8417-4f17-b491-4f105ed891a9'
    value: 'Sequential Notebook'
